In [1]:
a=1

In [2]:
a

1

# Data type

In [3]:
a = 123
b = -178
c = 0

In [4]:
print(a,b,c)

123 -178 0


In [6]:
print(a+b)
print(a**c)
print(a%b)
print(a//b)

-55
1
-55
-1


In [8]:
feed= "Python`s favorite food is perl"
feed

'Python`s favorite food is perl'

In [10]:
multiline = "Life is too short \n you need python"
print(multiline)

Life is too short 
 you need python


In [13]:
a="Python"
b=" is fun"
print(a+b)
a*3

Python is fun


'PythonPythonPython'

In [14]:
" i eat %d apples" % 3

' i eat 3 apples'

In [18]:
a= "python is the best choice"
print("a.count('t') : {}".format(a.count('t')))
print("a.find('t') : {}".format(a.find('t')))
print("a.find('d') : {}".format(a.find('d')))
print("'.'.join('abcd') : {}".format(".".join("abcd")))

a.count('t') : 3
a.find('t') : 2
a.find('d') : -1
'.'.join('abcd') : a.b.c.d


In [19]:
add=[1,2,3,4,5]
add[0]

1

In [20]:
add*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [22]:
a=["a","b","c"]
a.sort()
a

['a', 'b', 'c']

In [23]:
a=[1,2,3,4,5]
a.reverse()
a

[5, 4, 3, 2, 1]

# Tuple cant modify

In [24]:
a=(1,2,3,4)
a[1]= 4

TypeError: 'tuple' object does not support item assignment

# name, phone, birth => Key
# aaa,000111222, 1234 => Value

In [25]:
dic = {'name':'aaa','phone':'000111222','birth':'1234'}
dic

{'name': 'aaa', 'phone': '000111222', 'birth': '1234'}

In [26]:
dic["num"]=1
dic

{'name': 'aaa', 'phone': '000111222', 'birth': '1234', 'num': 1}

# There is no overlap

In [27]:
a={1:'a',1:'b'}
a

{1: 'b'}

In [28]:
dic.keys()

dict_keys(['name', 'phone', 'birth', 'num'])

In [29]:
dic.values()

dict_values(['aaa', '000111222', '1234', 1])

In [30]:
a1 = set([1,2,3,3])

In [31]:
a1

{1, 2, 3}

In [32]:
s2=set("hello")

In [33]:
s2

{'e', 'h', 'l', 'o'}

In [34]:
a=True
b=False
print("type_a : {}".format(type(a)))
print("type_a1 : {}".format(type(a1)))
print("type_dic : {}".format(type(dic)))

type_a : <class 'bool'>
type_a1 : <class 'set'>
type_dic : <class 'dict'>


In [35]:
1==1

True

In [36]:
1>2

False

In [37]:
a=[1,2,3]
b=a
b

[1, 2, 3]

In [38]:
a[1]=4
b

[1, 4, 3]

In [39]:
b=a[:]
a[1]=2
a

[1, 2, 3]

In [40]:
b

[1, 4, 3]

In [41]:
a,b=(1,2)
a=b=2
print(a,b)

2 2


In [42]:
a=3
b=5
a,b=b,a

In [43]:
print(a,b)

5 3


In [44]:
treeHit=0
while treeHit<10:
    treeHit+=1
    print("attact Tree : {}.".format(treeHit))
    if treeHit==10:
        print("a tree falls over")

attact Tree : 1.
attact Tree : 2.
attact Tree : 3.
attact Tree : 4.
attact Tree : 5.
attact Tree : 6.
attact Tree : 7.
attact Tree : 8.
attact Tree : 9.
attact Tree : 10.
a tree falls over


In [45]:
test_list = ["one","two","Three"]
for i in test_list:
    print(i)

one
two
Three


In [46]:
a=[(1,2),(3,4),(5,6)]
for (first,last) in a:
    print(first+last)

3
7
11


In [47]:
scores = [90,25,67,45,80]
num=0
for score in scores:
    num+=1
    if score>=60:
        print("number_{} is acceptance".format(num))
    else:
        print("number_{} is non_acceptance".format(num))

number_1 is acceptance
number_2 is non_acceptance
number_3 is acceptance
number_4 is non_acceptance
number_5 is acceptance


In [48]:
add=0
for i in range(1,10):
    add+=i
    print(add)

1
3
6
10
15
21
28
36
45


In [50]:
result = [i*j for i in range(1,10) for j in range(1,10)]
print(result)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 4, 6, 8, 10, 12, 14, 16, 18, 3, 6, 9, 12, 15, 18, 21, 24, 27, 4, 8, 12, 16, 20, 24, 28, 32, 36, 5, 10, 15, 20, 25, 30, 35, 40, 45, 6, 12, 18, 24, 30, 36, 42, 48, 54, 7, 14, 21, 28, 35, 42, 49, 56, 63, 8, 16, 24, 32, 40, 48, 56, 64, 72, 9, 18, 27, 36, 45, 54, 63, 72, 81]


In [77]:
result=[i for i in range(10) if i%2==0]

In [78]:
result

[0, 2, 4, 6, 8]

In [51]:
for i in range(10):
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 

In [52]:
class Calculator:
    def __init__(self):
        self.result=0
        
    def add(self, num):
        self.result+=num
        return self.result

In [53]:
print(Calculator().add(3))
print(Calculator().add(4))
cal1 = Calculator()
print(cal1.add(3))
print(cal1.add(4))

3
4
3
7


In [54]:
a=[3,2,1,0,3,4]
try :
    for num in a:
        print(4/num)
except ZeroDivisionError as e:
    print(e)

1.3333333333333333
2.0
4.0
division by zero


# Numpy and Matrix

In [55]:
import numpy as np

In [56]:
np.__version__

'1.19.2'

In [57]:
arrA=[1,2,3,4,5]
matrixA = np.array(arrA)
matrixB=np.array([1,2,3,'a','b'])
matrixB

array(['1', '2', '3', 'a', 'b'], dtype='<U21')

In [58]:
matrixB.shape

(5,)

In [59]:
matrixB.ndim

1

In [60]:
matrixB.size

5

In [61]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(1,30,5)

array([ 1,  6, 11, 16, 21, 26])

In [63]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [65]:
arr1 = np.arange(10,15)
arr2 = np.arange(20,25)

In [66]:
arr1+arr2

array([30, 32, 34, 36, 38])

In [67]:
arr1 - arr2

array([-10, -10, -10, -10, -10])

In [68]:
arr1[0],arr1[-1]

(10, 14)

In [69]:
matrixD=np.arange(1,31).reshape(5,6)

In [70]:
arr1

array([10, 11, 12, 13, 14])

In [71]:
arr1[1::2]

array([11, 13])

In [72]:
arr1[0:5:2]

array([10, 12, 14])

In [73]:
matrixD[::2,:]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18],
       [25, 26, 27, 28, 29, 30]])

In [74]:
matrixD[:,1::2]

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30]])