In [1]:
import numpy as np

In [3]:
X1=[[1,0,1],[1,1,0]]
X2=[[1,1],[0,1],[1,0]]

In [6]:
X1=np.matrix(X1)
X2=np.matrix(X2)

In [33]:
def Mean_Vector(x):
    result=[]
    for i in range(len(x)):
        make_x=np.sum(x[i])/(x.shape[1])
        result.append([make_x])# NX1행렬이 나와야 하기 때문에
    result=np.matrix(result)
    return result

In [34]:
result_Mean_X1=Mean_Vector(X1)
result_Mean_X2=Mean_Vector(X2)

In [35]:
result_Mean_X1, result_Mean_X2

(matrix([[0.66666667],
         [0.66666667]]),
 matrix([[1. ],
         [0.5],
         [0.5]]))

In [43]:
def Correlation_Matrix(x):
    result=(x*x.T)/(x.shape[1])
    return result

In [47]:
result_correlatin_X1=Correlation_Matrix(X1)
result_correlatin_X2=Correlation_Matrix(X2)

In [45]:
result_correlatin_X1

matrix([[0.66666667, 0.33333333],
        [0.33333333, 0.66666667]])

In [46]:
def Covariance_Matrix(x,y):
    result=x-y*y.T
    return result

In [49]:
result_covariance_X1=Covariance_Matrix(result_correlatin_X1,result_Mean_X1)
result_covariance_X2=Covariance_Matrix(result_correlatin_X2,result_Mean_X2)

In [50]:
result_covariance_X1,result_covariance_X2

(matrix([[ 0.22222222, -0.11111111],
         [-0.11111111,  0.22222222]]),
 matrix([[ 0.  ,  0.  ,  0.  ],
         [ 0.  ,  0.25, -0.25],
         [ 0.  , -0.25,  0.25]]))

In [51]:
Ex2 = [[77, 81, 74, 89, 78, 77, 75, 84, 79, 82, 69, 76, 74, 67, 74, 71, 67, 67, 70, 69]
       ,[72, 67, 74, 64, 71,67, 72, 68, 75, 70, 83, 78, 76, 82, 80, 77, 83, 84, 80, 80]
       ,[75, 68, 72, 68, 74, 68, 75, 73, 79, 72, 78, 75, 72, 74, 77, 70, 75, 79, 77, 76]]

In [53]:
Ex2=np.matrix(Ex2)

In [55]:
Ex2.shape

(3, 20)

In [56]:
result_Mean_Ex2=Mean_Vector(Ex2)
result_correlatin_Ex2=Correlation_Matrix(Ex2)
result_covariance_Ex2=Covariance_Matrix(result_correlatin_Ex2,result_Mean_Ex2)

In [57]:
result_Mean_Ex2, result_correlatin_Ex2, result_covariance_Ex2

(matrix([[75.  ],
         [75.15],
         [73.85]]),
 matrix([[5660.2 , 5604.3 , 5528.05],
         [5604.3 , 5682.75, 5564.5 ],
         [5528.05, 5564.5 , 5465.25]]),
 matrix([[ 35.2   , -31.95  , -10.7   ],
         [-31.95  ,  35.2275,  14.6725],
         [-10.7   ,  14.6725,  11.4275]]))