# Homework 4.3

In [1]:
Ex = [-4,-3,14,8,1,-5,-7,-4,-2,6,10,22,15,-15,-20]

In [2]:
import numpy as np

# Time Dataset Load
# Time => 2

In [3]:
def make_dataset(Ex,p):
    X=[Ex[i:i+p] for i in range(len(Ex)-p)]
    Y=[Ex[p+i] for i in range(len(Ex)-p)]
    return X, Y

In [4]:
X,Y=make_dataset(Ex,2)

# Remake dataset

In [5]:
X=np.array(X)
X=np.matrix(X)
X=X.T
remake_x=np.vstack((X[1],X[0]))

In [6]:
remake_x

matrix([[ -3,  14,   8,   1,  -5,  -7,  -4,  -2,   6,  10,  22,  15, -15],
        [ -4,  -3,  14,   8,   1,  -5,  -7,  -4,  -2,   6,  10,  22,  15]])

In [7]:
Y=np.array(Y)
Y=np.matrix(Y).T

In [8]:
def Cross_Correlation_Matrix(x,y):
    result=(x*y)/(x.shape[1])
    return result

In [9]:
def Correlation_Matrix(x):
    result=(x*x.T)/(x.shape[1])
    return result

In [10]:
Cor_X=Correlation_Matrix(remake_x)

In [11]:
Cor_X

matrix([[110.30769231,  40.69230769],
        [ 40.69230769,  94.23076923]])

In [12]:
Cross_cor=Cross_Correlation_Matrix(remake_x,Y)

In [13]:
Cross_cor

matrix([[ 62.84615385],
        [-36.23076923]])

In [14]:
result_seta=np.linalg.inv(Cor_X)*Cross_cor

In [15]:
result_seta

matrix([[ 0.84640871],
        [-0.75000017]])

# Mse

In [16]:
def mean_squre_error(X_var,Y_var,result_seta):
    result=0
    X_var=np.array(X_var.T)
    Y_var=np.array(Y_var.T)
    new_var=np.hstack((X_var,Y_var))
    seta=np.array(result_seta)
    for i, j, k in new_var:
        result+=((seta[1]*j + seta[0]*i)-k)**2
    result=result/13
    return result

In [17]:
mse=mean_squre_error(remake_x,Y.T,result_seta)

# Result

In [18]:
result_15 = -20*result_seta[0] + -15*result_seta[1]

In [19]:
result_15

matrix([[-5.67817165]])

# Covariance

In [20]:
def Mean_Vector(x):
    result=[]
    for i in range(len(x)):
        make_x=np.sum(x[i])/(x.shape[1])
        result.append([make_x])
    result=np.matrix(result)
    return result

In [21]:
mean_x=Mean_Vector(remake_x)

In [22]:
def Covariance_Matrix(x,y):
    result=x-y*y.T
    return result

In [23]:
result_Cov=Covariance_Matrix(Cor_X,mean_x)

In [24]:
result_num=0
for i in range(2):
    result_num+=np.diag(result_Cov,k=0)[i]
result_num=result_num/2

In [25]:
result_num

89.84023668639053

In [26]:
mse/result_num

array([0.66805256])

# Time => 4

In [27]:
X,Y=make_dataset(Ex,4)

In [28]:
X=np.array(X)
X=np.matrix(X)
X=X.T
remake_x=np.vstack((X[3],X[2],X[1],X[0]))

In [29]:
remake_x

matrix([[  8,   1,  -5,  -7,  -4,  -2,   6,  10,  22,  15, -15],
        [ 14,   8,   1,  -5,  -7,  -4,  -2,   6,  10,  22,  15],
        [ -3,  14,   8,   1,  -5,  -7,  -4,  -2,   6,  10,  22],
        [ -4,  -3,  14,   8,   1,  -5,  -7,  -4,  -2,   6,  10]])

In [30]:
Y=np.array(Y)
Y=np.matrix(Y).T

In [31]:
Cor_X=Correlation_Matrix(remake_x)

In [32]:
Cor_X

matrix([[111.72727273,  50.81818182, -10.45454545, -31.        ],
        [ 50.81818182, 109.09090909,  67.45454545,  14.45454545],
        [-10.45454545,  67.45454545,  89.45454545,  38.54545455],
        [-31.        ,  14.45454545,  38.54545455,  46.90909091]])

In [33]:
Cross_cor=Cross_Correlation_Matrix(remake_x,Y)

In [34]:
Cross_cor

matrix([[ 67.90909091],
        [-35.54545455],
        [-68.09090909],
        [-57.18181818]])

In [35]:
result_seta=np.linalg.inv(Cor_X)*Cross_cor

In [36]:
result_seta

matrix([[ 0.72572042],
        [-0.60482838],
        [ 0.02788513],
        [-0.57593977]])

In [37]:
def mean_squre_error(X_var,Y_var,result_seta):
    result=0
    X_var=np.array(X_var.T)
    Y_var=np.array(Y_var.T)
    new_var=np.hstack((X_var,Y_var))
    seta=np.array(result_seta)
    for i, j, k, h, u in new_var:
        result+=((seta[3]*h+seta[2]*k+seta[1]*j + seta[0]*i)-u)**2
    result=result/11
    return result

In [38]:
mse=mean_squre_error(remake_x,Y.T,result_seta)

In [39]:
result_15 = -20*result_seta[0] + -15*result_seta[1] +15*result_seta[2] + 22*result_seta[3]

In [40]:
result_15

matrix([[-17.69438056]])

# Covariance

In [41]:
def Mean_Vector(x):
    result=[]
    for i in range(len(x)):
        make_x=np.sum(x[i])/(x.shape[1])
        result.append([make_x])
    result=np.matrix(result)
    return result

In [42]:
mean_x=Mean_Vector(remake_x)

In [43]:
def Covariance_Matrix(x,y):
    result=x-y*y.T
    return result

In [44]:
result_Cov=Covariance_Matrix(Cor_X,mean_x)

# diag => (i,i)

In [45]:
result_num=0
for i in range(4):
    result_num+=np.diag(result_Cov,k=0)[i]

In [46]:
result_num=result_num/4

In [47]:
result_num

76.89669421487604

In [48]:
mse/result_num

array([0.52611175])